[	["Encore une victoire éclatante pour la libération des",
	 "peuples opprimés!... nan, en fait vous avez",
	 "juste tué des gens parce qu'il vous ont demandé vos papiers,",
	 "donc c'est pas vraiment une victoire pour la justice..."],
	["En tous cas, vous semblez combatre l'Empire",
	 "d'une drôle de manière. Il est peut-être temps de",
	 "rencontrer La Rébélion pour enfin avoir un rôle important",
	 "à jouer dans cette guerre intergalactique."]
] 
